# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gravity
email: xingbodg@gmail.com
description: The Liberal Jekyll Theme
baseurl: "https://qiuyangyueye.github.io/" # the subpath of your site, e.g. /blog
url: "https://qiuyangyueye.github.io/" # the base hostname & protocol for your site
twitter_username: qiuyangyueye
github_username:  qiuyangyueye

# Build settings
markdown: kramdown
